//Messages
export const FETCHING_MESSAGES_HAS_ERRORED = "FETCHING_MESSAGES_HAS_ERRORED";
export const MESSAGES_ARE_LOADING = "MESSAGES_ARE_LOADING";
export const MESSAGE_FETCHED_SUCCES = "MESSAGE_FETCHED_SUCCES";
export const RECEIVED_NEW_MESSAGE = "RECEIVED_NEW_MESSAGE";
export const MESSAGE_MARKED_DONE = "MESSAGE_MARKED_DONE";

//Challenges
export const RECEIVED_NEW_CHALLENGE = "RECEIVED_NEW_CHALLENGE";

//Locations
export const RECEIVED_NEW_LOCATION = "RECEIVED_NEW_LOCATION";
